package groovykickstart.everyday

import groovy.sql.Sql
import org.h2.jdbcx.JdbcDataSource


Sql db = new Sql(new JdbcDataSource(
        URL: 'jdbc:h2:file:~/personDB',
        user: 'sa',
        password: ''))


db.execute '''
    DROP   TABLE Person IF EXISTS;
    CREATE TABLE Person (
      personId   INTEGER GENERATED BY DEFAULT AS IDENTITY,
      firstName   VARCHAR(64),
      lastName    VARCHAR(64),
      dateOfBirth DATE
    );
    CREATE INDEX PersonIdx ON Person (personId);
    INSERT INTO Person (firstName, lastName, dateOfBirth) VALUES ('Jane', 'Doe', '1980-03-12');
'''

assert db.rows('SELECT * FROM Person').size() == 1


db.eachRow('SELECT firstName, lastName FROM Person') { row ->
    println row[0] + ' ' + row[1]
}


personSet = db.dataSet('Person')

personSet.add(
        firstName: 'Jack',
        lastName: 'Jones',
        dateOfBirth: '1970-10-11')

personSet.each {
    println it.firstName
}
